In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import mord

In [2]:
np.random.seed(42)

In [3]:
n_students = 200

In [4]:
# Attendance percentage (between 50% and 100%)
attendance = np.random.randint(50, 101, n_students)

In [5]:
# Study hours per week (between 1 to 20)
study_hours = np.random.randint(1, 21, n_students)

In [6]:
X = np.column_stack((study_hours, attendance))

In [7]:
X

array([[  5,  88],
       [  1,  78],
       [ 19,  64],
       [ 10,  92],
       [ 12,  57],
       [ 15,  70],
       [  9,  88],
       [ 20,  68],
       [ 17,  72],
       [ 17,  60],
       [ 20,  60],
       [ 12,  73],
       [  7,  85],
       [  2,  89],
       [  3,  73],
       [ 17,  52],
       [  5,  71],
       [ 17,  51],
       [ 17,  73],
       [ 17,  93],
       [  2,  79],
       [  2,  87],
       [  5,  51],
       [  1,  70],
       [  1,  82],
       [ 19,  61],
       [  2,  71],
       [ 12,  93],
       [  6,  74],
       [  4,  98],
       [ 11,  76],
       [ 17,  91],
       [  6,  77],
       [  5,  65],
       [ 20,  64],
       [  2,  96],
       [  6, 100],
       [ 11,  93],
       [ 16,  52],
       [ 16,  86],
       [  1, 100],
       [  9,  56],
       [  6,  70],
       [ 16,  58],
       [  3,  88],
       [ 20,  67],
       [  4,  53],
       [ 19,  74],
       [  3,  63],
       [ 19,  99],
       [ 20,  58],
       [  7,  75],
       [ 20,

In [8]:
# Add score logic
score = (study_hours * 2) + (attendance * 0.5)

In [9]:
y = np.where(
    score < 60, 0,             # 0 = Low
    np.where(score < 80, 1, 2) # 1 = Med, 2 = High
)

In [10]:
y

array([0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 2, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 2, 1, 0, 1, 0, 0, 1, 0, 2, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 2, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 2, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 2, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 2, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 2, 1,
       0, 1, 0, 2, 0, 0, 0, 1, 1, 0, 1, 0, 2, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 2, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1])

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [12]:
# Initial ordinal logistic regression model
# model = mord.LogisticAT() # Adjascent Threhold
model = mord.LogisticIT() # Inteermediate Threhold

In [13]:
model.fit(X_train, y_train)

,alpha,1.0
,verbose,0
,max_iter,1000


In [14]:
# Make prediction
y_pred = model.predict(X_test)

In [15]:
y_pred

array([2, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 2, 0, 1, 0, 1, 0, 2, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0])

In [16]:
print(accuracy_score(y_test, y_pred))

0.95
